### ISSUE TITLE
bug: workflows doesn't trigger anymore 😢 

### ISSUE THREAD

**Issue by Grraahaam** [SvanBoxel/organization-workflows#42]
Heyaa! 👋🏽 

This app have been working great for some weeks now but suddenly stopped processing events, a detailed post by myself on Github's community forum : https://github.community/t/organization-worklfow-not-receiving-any-events-anymore/256343

*Preview*
> I’m using the organization-workflow 1 app to listen to some events in given repositories in my organization, but since approximately a week it seems the app doesn’t receive any events or at least doesn’t get triggered by them.
> 
> The app should dispatch any “push” event to the organization .github repository, according the “how it works” section. And I have correctly created a workflow file listening on repository_dispatch of org-workflow-bot type, since everything worked as expected… :eyes:
> 
> Any update on GH that might altered the event/auth/app behaviors? :thinking:
> 
> Or any alternative to run organization workflows, listening on the all/given repositories? GH’s roadmap about it : Actions: Organization and enterprise workflows · Issue #52 · github/roadmap · GitHub
> 
> Thanks in advance :v:
> 
> Edit 1: The repository is private as we don’t want to share those workflows, and we’re using Github Teams plan
> 
> Edit 2: I’ve just tested putting my test organization repos (.github + my-demo-app) as public repos and processed my pushes again and still got nothing, so it becomes hard to understand where the issue is coming from, now…

Since this is a topic that often comes back in the forum, about how to DRY and avoid having to maintain the same workflows across all the repositories, maybe it's worth a look? 🤔 

And the roadmap doesn't give any specific date for this feature, planned to be natively supported by GH if I'm right

Any of you experiencing the same issue, or is it just me? 🙏🏽 

Thanks ✌🏽

**Comment by SvanBoxel** [comment]
I can confirm something is broken. Will look into it this weekend. Thanks for flagging.

**Comment by Grraahaam** [comment]
Did you had time to dig into it? Is there anything I can help with, any hint? Is it related to an update on GH's side since your app didn't changed since mid 2021? 🤔

**Comment by SvanBoxel** [comment]
Thanks for being patient with me. This should be fixed now, but could you @Grraahaam validate this for me before we close this issue?

Thanks!

**Comment by Grraahaam** [comment]
It's back on track on our side (so far), thanks a lot for your time @SvanBoxel ! 🙌🏽 

Just curious, what have been done to fix it, did you just bumped the underlying packages? As in your latest [commits](https://github.com/SvanBoxel/organization-workflows/commits/main) 🤔

**Comment by SvanBoxel** [comment]
No, one of the containers crashed and couldn't easily be restarted. That package update was only to trigger and test a new deployment, but nothing in the application code was actually broken.

**Comment by mdupire** [comment]
Hello, the problem is back. Sometimes the detection and the trigger is very long. But since yesterday, nothing triggers.
